### ISSUE TITLE
Accept EULA in headless mode

### ISSUE THREAD

**Issue by robingarcia** [10XGenomics/loupeR#16]
How can I confirm loupeR::setup() in headless mode (e.g. HPC cluster) with yes?

?loupeR::setup() does not give any hints for this.

**Comment by esiegel** [comment]
Is this a blocker, as in you have no way of installing `loupeR` in an interactive fashion, or an inconvenience.  I totally agree that this isn't the best user experience, but it was explicitly required by our legal team.  I would write to support@10xgenomics.com and see if they have anything to say.

**Comment by esiegel** [comment]
After speaking with legal, I don't think this is something that we can support.  Allowing a script to automatically agree to the EULA would make proving that the users have agreed to the EULA more challenging.  I do apologize for any inconvenience.

Please reopen if this is a blocker or if you have more to add.

**Comment by SergejN** [comment]
Totally agree, I face the same issue now - I need to export Loupe files from the nextflow pipeline, but cannot put loupeR into the container because of `setup()`..
As a potential way to satisfy the legal, would it be possible to create a different version of `loupeR` that explicitly requires the user to agree to EULA before it can even be downloaded? I mean this is how you get the Loupe Browser in the first place..

**Comment by esiegel** [comment]
I have seen the environment variable technique used elsewhere.  I can see what legal says.

You can always run the interactive install in the docker container.  See this https://stackoverflow.com/a/40859529/28486
