### ISSUE TITLE
Normalized data

### ISSUE THREAD

**Issue by NadineBestard** [10XGenomics/loupeR#28]
Thanks for developing this tool! This is the crucial piece Loupe Browser was missing in order to use it in combination with more advanced analysis. 
However, I am a bit disappointed regarding the normalisation. I see the Cloupe file can only store the raw counts, and Loupe Browser does a rather simple normalisation. It would be great if the "data" slot and/or the SCTransform assay could be added and then made available in the "scale value" drop-down menu on top of the available "Log" and "LogNorm".

**Comment by esiegel** [comment]
The reason SCTransform data is not available in Loupe is because Loupe itself does not support storing non-integer values. One option is to round your data to integers and then create the Loupe file with the create_loupe function in LoupeR. Please note that this is not supported and at your own risk in terms of analysis and interpretation. We do not recommend performing differential expression on transformed data. We are tracking requests for SCTransform data in Loupe and will add your voice to the open feature request.
