### ISSUE TITLE
Spot Deconvolution in Loupe with Seurat-processed object? 

### ISSUE THREAD

**Issue by rln0005** [10XGenomics/loupeR#56]
Hi 10x Team, 

I have successfully converted my Seurat processed object into a Loupe file and visualized quite nicely in Loupe. However, I noticed the "Spot Deconvolution" tab is no longer available on this new Loupe file. Can you clarify if there's a way to maintain that function in Loupe with the Seurat-processed data, or if there's a way to incorporate this information into the Seurat object prior to converting to Loupe (ie, such as using STdeconvolve in R...?) 

Thanks in advance,
Rebecca

**Comment by gmjoseph** [comment]
Hi @rln0005

Thanks for raising this interesting issue. Spot deconvolution is a spatial feature and relies on pre-existing data from our pipelines, which we generate. We don't currently support spatial data, or generating spot deconvolution data in loupeR. @dylanwebster  might have further information to provide on those two topics.

**Comment by dylanwebster** [comment]
Hi @rln0005 , as gmjoseph mentioned, LoupeR currently only supports single cell gene expression data. I will close this issue for now, since there are no workarounds or fixes we can presently apply for deconvolution results from LoupeR generated .cloupe files, but we can update if LoupeR is updated to support Visium data. 

I am curious in learning more if you are already using LoupeR for Visium data with a workaround on your end. If you are interested in chatting more about your use case and how we could address it, please feel free to email me at dylan.webster@10xgenomics.com.
