### ISSUE TITLE
Creating .loupe file with 2um bins 

### ISSUE THREAD

**Issue by YimengQiao** [10XGenomics/loupeR#65]
Hi, I have a 2um-binned HD dataset, including 

- all the barcodes, features, matrix data, 
- full-resolution HE image
- a tissue_positions.parquet data file, contains the X coordinate, Y coordinate, pixel_x_on_full_resolution_HE, pixel_y_on_full_resolution_HE  of each barcode

I would like to ask it is possible for me to create a .loupe file with the above data? 

My goal is to map each 2um-bin with its corresponding HE image positions and visualize them via Loupe browser, so that I can annotate some bins that I'm interested in the HE image and extract these annotated bins' barcodes for further analysis. I noticed that the standard method seems to be spaceranger, however, the parameter 'custom_bin_size' of spaceranger does not support 2um. So I am thinking about whether I can just use the counts matrix, HE image, and corresponding position parquet files to create a .loupe file. Since I just want to extract some interesting barcodes, the accuracy of gene expression of each 2um bin is not so important to me.

Looking forward to your reply!

**Comment by EvanWinget** [comment]
Hello,

Thank you for expressing interest in visualizing the 2µm binned HD dataset in Loupe and clarifying your goals. 

Unfortunately, Loupe does not currently support bin sizes less than 8µm for Visium HD. My recommendation would be to identify the X and Y coordinates of interest in your HE image using imaging software, and then to use the tissue positions parquet file at 2µm in order to find the Visium HD barcode associated with these image coordinates.

We've recorded your interest in visualization at the 2µm level and will certainly consider this on our roadmap for the future. If you have additional questions regarding your analysis of Visium HD data, please contact support@10xgenomics.com for further assistance.

Thanks,
Evan
